//Get all elements
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const RESET_PRODUCTS = 'RESET_PRODUCT'
//Get single Item
export const FETCH_PRODUCT_BY_ID_REQUEST = 'FETCH_PRODUCT_BY_ID_REQUEST';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';
export const RESET_PRODUCT_BY_ID = 'RESET_PRODUCT_BY_ID';
//Get Carousel Item 
export const FETCH_CAROUSEL_REQUEST = 'FETCH_CAROUSEL_REQUEST';
export const FETCH_CAROUSEL_SUCCESS = 'FETCH_CAROUSEL_SUCCESS';
export const FETCH_CAROUSEL_FAILURE = 'FETCH_CAROUSEL_FAILURE';
